---
- hosts: localhost
  become: sudo

  tasks:
    - name: Installing Zsh
      sudo: yes
      apt: pkg=zsh state=present

    - name: Cloning oh-my-zsh
      become: kreizo
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh
