---
- hosts: localhost
  become: sudo

  tasks:
    - name: Install git
      apt: pkg=git state=present
    - name: Configure git user.name
      local_action: shell git config --global user.name "kreiz0"
    - name: Configure git user.email
      local_action: shell git config --global user.email "thekreizo@gmail.com"
    - name: Configure git core.editor
      local_action: shell git config --global core.editor vim
    - name: Configure git merge.tool
      local_action: shell git config --global merge.tool vimdiff
    - name: Configure git diff3
      local_action: shell git config --global merge.conflictstyle diff3
    - name: Configure git mergetool.prompt
      local_action: shell git config --global mergetool.prompt false
